module.exports = {
  purge: [
    './*.php',
    './blocks/**/*.php',
    './components/**/*.php',
    './partials/**/*.php',
    './templates/**/*.php',
    './assets/scripts/*.js',
  ],
  corePlugins: {
    container: false,
  },
  theme: {
    colors: {
      orange: '#FA8C5C',
      navy: '#1B2040',
      navyLight: '#27356D',
      blue: '#4A73F3',
      grey: '#F2F2F2',
      white: '#FFFFFF',
      pink: '#FCECE8',
      transparent: 'transparent',
    },
    fontFamily: {
      reg: ['lexend-regular'],
      med: ['lexend-medium'],
      bold: ['lexend-bold'],
    },
    fontSize: {
      14: '0.875rem',
      16: '1rem',
      18: '1.125rem',
      20: '1.25rem',
      22: '1.375rem',
      26: '1.625rem',
      30: '1.875rem',
      32: '2rem',
      36: '2.25rem',
      40: '2.5rem',
      46: '2.875rem',
      60: '3.75rem',
      65: '4.0625rem',
      70: '4.375rem',
      80: '5rem',
    },
  },
  variants: {},
  plugins: [require('@tailwindcss/typography', 'tailwindcss-gradients')],
}
